# Generated by Django 5.0.1 on 2024-06-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('parents_name', models.CharField(max_length=30)),
                ('current_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=255)),
                ('hobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('technologies_worked_on', models.CharField(blank=True, default='', max_length=255)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('pass_year', models.IntegerField(max_length=4)),
                ('percentage', models.FloatField(max_length=4)),
                ('board', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=100)),
                ('technologies_used', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('pass_year', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('board', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_languages', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('pass_year', models.IntegerField(max_length=4)),
                ('percentage', models.FloatField(max_length=4)),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createresume.personaldetails')),
            ],
        ),
    ]
