# Generated by Django 5.0.6 on 2024-07-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createresume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeeducation',
            name='pass_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universityeducation',
            name='pass_year',
            field=models.IntegerField(),
        ),
    ]
